---
openapi: 3.0.1
info:
  title: Good Night API
  version: v1
  description: Sleep tracking API with social features - clock in/out, track sleep
    records, and see friends' sleep patterns.
  contact:
    name: API Support
    email: support@goodnight.com
paths:
  "/api/v1/users/{user_id}/follows":
    parameters:
    - name: user_id
      in: path
      description: Current user ID
      required: true
      schema:
        type: integer
    get:
      summary: List user followings
      tags:
      - Follows
      description: Get a paginated list of users that the current user follows
      parameters:
      - name: page
        in: query
        required: false
        description: 'Page number (default: 1)'
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        description: 'Items per page (default: 20)'
        schema:
          type: integer
      responses:
        '200':
          description: successful
        '404':
          description: user not found
    post:
      summary: Follow a user
      tags:
      - Follows
      description: Follow another user
      parameters:
      - name: target_user_id
        in: query
        required: true
        description: ID of user to follow
        schema:
          type: integer
      responses:
        '201':
          description: successfully followed
        '422':
          description: unable to follow
        '404':
          description: user not found
  "/api/v1/users/{user_id}/follows/{target_user_id}":
    parameters:
    - name: user_id
      in: path
      description: Current user ID
      required: true
      schema:
        type: integer
    - name: target_user_id
      in: path
      description: ID of user to unfollow
      required: true
      schema:
        type: integer
    delete:
      summary: Unfollow a user
      tags:
      - Follows
      description: Unfollow a user
      responses:
        '200':
          description: successfully unfollowed
        '422':
          description: unable to unfollow
        '404':
          description: user not found
  "/api/v1/users/{user_id}/sleep_records":
    parameters:
    - name: user_id
      in: path
      description: Current user ID
      required: true
      schema:
        type: integer
    post:
      summary: Clock in/out for sleep
      tags:
      - Sleep Records
      description: Clock in to start sleep tracking or clock out to end current sleep
        session
      responses:
        '201':
          description: successfully clocked in
        '200':
          description: successfully clocked out
        '404':
          description: user not found
    get:
      summary: List user sleep records
      tags:
      - Sleep Records
      description: Get a paginated list of user's sleep records
      parameters:
      - name: page
        in: query
        required: false
        description: 'Page number (default: 1)'
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        description: 'Items per page (default: 20)'
        schema:
          type: integer
      responses:
        '200':
          description: successful
        '404':
          description: user not found
  "/api/v1/users/{user_id}/sleep_records/friends_sleep_records":
    parameters:
    - name: user_id
      in: path
      description: Current user ID
      required: true
      schema:
        type: integer
    get:
      summary: List friends sleep records
      tags:
      - Sleep Records
      description: Get sleep records from users that current user follows, from past
        week, sorted by duration
      parameters:
      - name: page
        in: query
        required: false
        description: 'Page number (default: 1)'
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        description: 'Items per page (default: 20)'
        schema:
          type: integer
      responses:
        '200':
          description: successful
        '404':
          description: user not found
  "/api/v1/users":
    get:
      summary: List users
      tags:
      - Users
      description: Get a paginated list of all users
      parameters:
      - name: page
        in: query
        required: false
        description: 'Page number (default: 1)'
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        description: 'Items per page (default: 20)'
        schema:
          type: integer
      responses:
        '200':
          description: successful
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      description: User ID
      required: true
      schema:
        type: integer
    get:
      summary: Show user
      tags:
      - Users
      description: Get details of a specific user
      responses:
        '200':
          description: successful
        '404':
          description: not found
servers:
- url: http://localhost:3000
  description: Development server
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: api.goodnight.com
  description: Production server
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: John Doe
        created_at:
          type: string
          format: datetime
          example: '2025-09-11T07:56:47Z'
      required:
      - id
      - name
      - created_at
    SleepRecord:
      type: object
      properties:
        id:
          type: integer
          example: 1
        user_id:
          type: integer
          example: 1
        sleep_at:
          type: string
          format: datetime
          example: '2025-09-29T22:00:00Z'
        wake_up_at:
          type: string
          format: datetime
          example: '2025-09-30T06:00:00Z'
          nullable: true
        duration_in_seconds:
          type: integer
          example: 28800
          nullable: true
        created_at:
          type: string
          format: datetime
          example: '2025-09-29T22:00:00Z'
      required:
      - id
      - user_id
      - sleep_at
      - created_at
    PaginationMeta:
      type: object
      properties:
        current_page:
          type: integer
          example: 1
        per_page:
          type: integer
          example: 20
        total_pages:
          type: integer
          example: 5
        total_count:
          type: integer
          example: 100
    Error:
      type: object
      properties:
        error:
          type: string
          example: Resource not found
